In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [32]:
df = pd.read_excel('./Data/영어크롤링임베딩.xlsx.xlsx', index_col = 0)
df.head()

Date          Name  Score  \
0  January 26, 2020  Bernard Reis      1   
1  January 18, 2020  Gordon Inman      2   
2  January 18, 2020       MrDurma      4   
3  January 26, 2020      K Kostas      3   
4  January 17, 2020    Greg Evans      3   

                                              Review  like  \
0  completely frustrating experience  paid extra ...     7   
1  some good features  but this app isn t very sm...     8   
2  this app works perfectly  it allowed us to dow...     2   
3  good but not great for an app by lg  not the m...     1   
4  app is useful but limited and requires some up...     1   

                                               token  \
0  ['complet', 'frustrat', 'experi', 'paid', 'ext...   
1  ['good', 'featur', 'app', 'smart', 'would', 't...   
2  ['app', 'work', 'perfectli', 'allow', 'us', 'd...   
3  ['good', 'great', 'app', 'lg', 'user', 'interf...   
4  ['app', 'use', 'limit', 'requir', 'updat', 'wi...   

                                              vector  
0  [-0.13434231 -0.1759159  -0.17113061  0.185344...  
1  [ 0.03618171 -0.01203014  0.02510391 -0.074861...  
2  [ 0.02501285  0.1104259   0.1731757  -0.101633...  
3  [-0.25846013  0.17875025 -0.2734563  -0.263128...  
4  [ 0.29014143  0.19826113 -0.2062311   0.291473...

In [33]:
df.isnull().sum()

Date      0
Name      0
Score     0
Review    0
like      0
token     0
vector    0
dtype: int64

In [34]:
# array형태를 숫자형태로 변환

def erase_double_blank(string):
    result = string
    while "  " in result:
        result = result.replace("  ", " ")
    while ",," in result:
        result = result.replace(",,", ",")
    while ", ," in result:
        result = result.replace(", ,", ",")
    result = result.replace("[, ", "[")
    result = result.replace(", ]", "]")
    return result

df["vector"] = df["vector"].apply(lambda x : x.replace("\n", " "))
df["vector"] = df["vector"].apply(lambda x : x.replace(" ", ", "))
df["vector"] = df["vector"].apply(lambda x : erase_double_blank(x))
 
df["vector"] = df["vector"].apply(lambda x : ast.literal_eval(x))

In [36]:
df.head()

Date          Name  Score  \
0  January 26, 2020  Bernard Reis      1   
1  January 18, 2020  Gordon Inman      2   
2  January 18, 2020       MrDurma      4   
3  January 26, 2020      K Kostas      3   
4  January 17, 2020    Greg Evans      3   

                                              Review  like  \
0  completely frustrating experience  paid extra ...     7   
1  some good features  but this app isn t very sm...     8   
2  this app works perfectly  it allowed us to dow...     2   
3  good but not great for an app by lg  not the m...     1   
4  app is useful but limited and requires some up...     1   

                                               token  \
0  ['complet', 'frustrat', 'experi', 'paid', 'ext...   
1  ['good', 'featur', 'app', 'smart', 'would', 't...   
2  ['app', 'work', 'perfectli', 'allow', 'us', 'd...   
3  ['good', 'great', 'app', 'lg', 'user', 'interf...   
4  ['app', 'use', 'limit', 'requir', 'updat', 'wi...   

                                              vector  
0  [-0.13434231, -0.1759159, -0.17113061, 0.18534...  
1  [0.03618171, -0.01203014, 0.02510391, -0.07486...  
2  [0.02501285, 0.1104259, 0.1731757, -0.10163309...  
3  [-0.25846013, 0.17875025, -0.2734563, -0.26312...  
4  [0.29014143, 0.19826113, -0.2062311, 0.2914731...

In [40]:
from sklearn.cluster import KMeans

In [39]:
k = 3

model = KMeans(n_clusters = k)

In [42]:
arr_vec = np.array(list(df['vector']))

In [43]:
model.fit(arr_vec)

C:\Users\125\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] 지정된 파일을 찾을 수 없습니다
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\125\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\Users\125\anaconda3\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\125\anaconda3\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        

KMeans(n_clusters=3)

In [47]:
df['kmeans'] = model.fit_predict(arr_vec)

In [48]:
df.head()

Date          Name  Score  \
0  January 26, 2020  Bernard Reis      1   
1  January 18, 2020  Gordon Inman      2   
2  January 18, 2020       MrDurma      4   
3  January 26, 2020      K Kostas      3   
4  January 17, 2020    Greg Evans      3   

                                              Review  like  \
0  completely frustrating experience  paid extra ...     7   
1  some good features  but this app isn t very sm...     8   
2  this app works perfectly  it allowed us to dow...     2   
3  good but not great for an app by lg  not the m...     1   
4  app is useful but limited and requires some up...     1   

                                               token  \
0  ['complet', 'frustrat', 'experi', 'paid', 'ext...   
1  ['good', 'featur', 'app', 'smart', 'would', 't...   
2  ['app', 'work', 'perfectli', 'allow', 'us', 'd...   
3  ['good', 'great', 'app', 'lg', 'user', 'interf...   
4  ['app', 'use', 'limit', 'requir', 'updat', 'wi...   

                                              vector  kmeans  
0  [-0.13434231, -0.1759159, -0.17113061, 0.18534...       1  
1  [0.03618171, -0.01203014, 0.02510391, -0.07486...       1  
2  [0.02501285, 0.1104259, 0.1731757, -0.10163309...       1  
3  [-0.25846013, 0.17875025, -0.2734563, -0.26312...       0  
4  [0.29014143, 0.19826113, -0.2062311, 0.2914731...       2

In [49]:
# DBSCAN

from sklearn.cluster import DBSCAN

In [64]:
model_dbscan = DBSCAN(eps = 0.9, min_samples = 5)

model_dbscan.fit(arr_vec)

DBSCAN(eps=0.9)

In [65]:
df['dbscan'] = model_dbscan.fit_predict(arr_vec)

In [66]:
df.head()

Date          Name  Score  \
0  January 26, 2020  Bernard Reis      1   
1  January 18, 2020  Gordon Inman      2   
2  January 18, 2020       MrDurma      4   
3  January 26, 2020      K Kostas      3   
4  January 17, 2020    Greg Evans      3   

                                              Review  like  \
0  completely frustrating experience  paid extra ...     7   
1  some good features  but this app isn t very sm...     8   
2  this app works perfectly  it allowed us to dow...     2   
3  good but not great for an app by lg  not the m...     1   
4  app is useful but limited and requires some up...     1   

                                               token  \
0  ['complet', 'frustrat', 'experi', 'paid', 'ext...   
1  ['good', 'featur', 'app', 'smart', 'would', 't...   
2  ['app', 'work', 'perfectli', 'allow', 'us', 'd...   
3  ['good', 'great', 'app', 'lg', 'user', 'interf...   
4  ['app', 'use', 'limit', 'requir', 'updat', 'wi...   

                                              vector  kmeans  dbscan  
0  [-0.13434231, -0.1759159, -0.17113061, 0.18534...       1       0  
1  [0.03618171, -0.01203014, 0.02510391, -0.07486...       1       0  
2  [0.02501285, 0.1104259, 0.1731757, -0.10163309...       1       0  
3  [-0.25846013, 0.17875025, -0.2734563, -0.26312...       0      -1  
4  [0.29014143, 0.19826113, -0.2062311, 0.2914731...       2      -1

In [67]:
df['dbscan'].unique()

array([ 0, -1,  1])

In [68]:
# 계층적 군집분석

from sklearn.cluster import AgglomerativeClustering

In [69]:
model_agg = AgglomerativeClustering(n_clusters= 3)

In [70]:
model_agg.fit(arr_vec)

AgglomerativeClustering(n_clusters=3)

In [71]:
df['agg'] = model_agg.fit_predict(arr_vec)

In [72]:
df.head()

Date          Name  Score  \
0  January 26, 2020  Bernard Reis      1   
1  January 18, 2020  Gordon Inman      2   
2  January 18, 2020       MrDurma      4   
3  January 26, 2020      K Kostas      3   
4  January 17, 2020    Greg Evans      3   

                                              Review  like  \
0  completely frustrating experience  paid extra ...     7   
1  some good features  but this app isn t very sm...     8   
2  this app works perfectly  it allowed us to dow...     2   
3  good but not great for an app by lg  not the m...     1   
4  app is useful but limited and requires some up...     1   

                                               token  \
0  ['complet', 'frustrat', 'experi', 'paid', 'ext...   
1  ['good', 'featur', 'app', 'smart', 'would', 't...   
2  ['app', 'work', 'perfectli', 'allow', 'us', 'd...   
3  ['good', 'great', 'app', 'lg', 'user', 'interf...   
4  ['app', 'use', 'limit', 'requir', 'updat', 'wi...   

                                              vector  kmeans  dbscan  agg  
0  [-0.13434231, -0.1759159, -0.17113061, 0.18534...       1       0    2  
1  [0.03618171, -0.01203014, 0.02510391, -0.07486...       1       0    2  
2  [0.02501285, 0.1104259, 0.1731757, -0.10163309...       1       0    1  
3  [-0.25846013, 0.17875025, -0.2734563, -0.26312...       0      -1    0  
4  [0.29014143, 0.19826113, -0.2062311, 0.2914731...       2      -1    1

In [73]:
from sklearn.metrics import silhouette_score

In [78]:
print(silhouette_score(arr_vec, df['kmeans'] , metric = 'euclidean'))

0.10869914301720268


In [79]:
print(silhouette_score(arr_vec, df['dbscan'] , metric = 'euclidean'))

0.16488259939751582


In [80]:
print(silhouette_score(arr_vec, df['agg'] , metric = 'euclidean'))

0.04425296305591335


In [81]:
from sklearn.decomposition import PCA

In [84]:
#차원축소 (주성분)
pca = PCA(n_components = 2)
principalComponents = pca.fit_transform(arr_vec)

In [85]:
principalComponents

array([[-0.21418885, -0.11962035],
       [-0.50684531, -0.0236534 ],
       [-0.3523773 , -0.26012009],
       ...,
       [ 0.67121777, -0.42223748],
       [-0.28076808,  0.0240766 ],
       [ 0.20371838,  0.0656116 ]])

In [86]:
df_pca = pd.DataFrame(principalComponents , columns = ['pca1','pca2'])

In [87]:
df_pca.head()

pca1      pca2
0 -0.214189 -0.119620
1 -0.506845 -0.023653
2 -0.352377 -0.260120
3  0.424192 -0.370166
4  0.385409  0.583861

In [89]:
df_pca[['kmeans', 'dbscan','agg']] = df[['kmeans', 'dbscan','agg']]

In [ ]:
plt.figure(figsize = (10,7))

plt.scatter(df_pca['pca1'], df_pca['pca2'])
plt.show()

In [93]:
color = ['red','blue','green']

In [103]:
from tqdm import tqdm

In [ ]:
for i in tqdm(df_pca.index):
    plt.scatter(df_pca['pca1'].loc[i], df_pca['pca2'].loc[i] , color = color[df_pca['kmeans'].loc[i]])

In [109]:
'''
for i in tqdm(df_pca.index):
    plt.scatter(df_pca['pca1'].loc[i], df_pca['pca2'].loc[i] , color = color[df_pca['dbscan'].loc[i]])

for i in tqdm(df_pca.index):
    plt.scatter(df_pca['pca1'].loc[i], df_pca['pca2'].loc[i] , color = color[df_pca['agg'].loc[i]])
    '''

"\nfor i in tqdm(df_pca.index):\n    plt.scatter(df_pca['pca1'].loc[i], df_pca['pca2'].loc[i] , color = color[df_pca['dbscan'].loc[i]])\n\nfor i in tqdm(df_pca.index):\n    plt.scatter(df_pca['pca1'].loc[i], df_pca['pca2'].loc[i] , color = color[df_pca['agg'].loc[i]])\n    "

# **와인 데이터셋**

In [130]:
wine= pd.read_csv('./Data/wine.csv.csv', index_col = 0)

In [131]:
wine = wine.iloc[:,2:-1]

In [123]:
from sklearn.preprocessing import MinMaxScaler

In [125]:
scaler = MinMaxScaler()

In [135]:
scale_df  = pd.DataFrame(scaler.fit_transform(wine), columns = wine.columns)

In [142]:
md_db_wine = DBSCAN(eps = 0.9)

In [143]:
md_db_wine.fit(scale_df)

DBSCAN(eps=0.9)

In [146]:
scale_df['dbscan'] = md_db_wine.fit_predict(scale_df)

In [147]:
scale_df['dbscan'].unique()

array([ 0, -1])

In [196]:
md_km_wine = KMeans(n_clusters=2)

In [197]:
md_km_wine.fit(scale_df)

KMeans(n_clusters=2)

In [198]:
scale_df['kmeans'] = md_km_wine.fit_predict(scale_df)

In [149]:
wine_pca = PCA(n_components= 3)
pca_result = wine_pca.fit_transform(scale_df)

In [151]:
wine_pca = pd.DataFrame(pca_result, columns = ['pca1','pca2','pca3'])

In [167]:
wine_pca['cluster'] = pd.DataFrame(scale_df['dbscan'])

In [199]:
wine_pca['kcluster'] = pd.DataFrame(scale_df['kmeans'])

In [200]:
wine_pca

pca1      pca2      pca3  cluster  kcluster
0    -0.381786  0.030563 -0.066950        0         0
1    -0.093934 -0.069457  0.051736        0         0
2    -0.037514 -0.017639  0.000192        0         0
3    -0.182757  0.092703  0.077932        0         0
4    -0.182757  0.092703  0.077932        0         0
...        ...       ...       ...      ...       ...
6492  0.172226 -0.268008  0.081547        0         1
6493  0.253854 -0.217291  0.137032        0         1
6494  0.219470 -0.210519  0.049184        0         1
6495  0.168316 -0.344536  0.143001        0         1
6496  0.169243 -0.083785 -0.011513        0         1

[6497 rows x 5 columns]

In [192]:
from mpl_toolkits.mplot3d import Axes3D
# 3D 시각화 함수
def plot_clusters_3d(df, label_col, title):
    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(111, projection='3d')
    sc = ax.scatter(df['pca1'], df['pca2'], df['pca3'], 
                    c=df[label_col], cmap='tab10', s=50, alpha=0.8)
    ax.set_title(title)
    ax.set_xlabel("PCA 1")
    ax.set_ylabel("PCA 2")
    ax.set_zlabel("PCA 3")
    #fig.colorbar(sc, ax=ax, label="Cluster")
    plt.tight_layout()
    plt.show()

In [ ]:
plot_clusters_3d(wine_pca, 'cluster' ,'pca')

In [ ]:
plot_clusters_3d(wine_pca, 'kcluster' ,'pca')